--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Aurora-MC/AfterLife
branches:
- master
projects:
  AfterLife:
    path: ""
    libs:
    - src: thebigsmileXD/customui/customui
      version: ^3.0.0
...
