#enable floating texts.
#true: false:
texts-enabled: true

#how many players to display
texts-top: 5

#setts the title for each leaderboard
texts-title:
  levels: "&b< PvP Levels Leaderboard >"
  kills: "&b< Kills Leaderboard >"
  kdr: "&b< K/D Ratio Leaderboard >"
  streaks: "&b< Top Killstreaks >"

#Disables PvP at spawn... uses server default level,
#if want to use custom level set this to false and use (no-PvP-in-level)
no-PvP-at-spawn: true

#disables PvP in specified world
#works if no-PvP-at-spawn: is set to false
#may add worlds!
no-PvP-in-level:
  - "world1"
  - "world2"
  - "world3"

#choose to use unique "form" or "standard" message to display stats
#form requires FormApi plugin
#methods => "form" "standard"
profile-method: "standard"

#choose between 'custom' or 'default'
#custom bypasses the death 'main menu' screen and default does not
death-method: "custom"

#use built in level up system that adds levels on kill and removes level on death
#choose 'false' if you already have a level up plugin
#true: false:
use-levels: true

#use level up timer
#adds xp over time
#(example) stay online to gain xp
use-level-up-timer: true

#amount of xp to be given on kill
add-level-xp-amount: 50

#amout of xp to be lost on death
loose-level-xp-amount: 10

#how much xp is required for level up
xp-levelup-amount: 1000

#-------------------------------------------------------------------------------------------------------------------------
# DATA STORING!!!
#
# How you want to store data
#
# - online database (use if you have more than one server and want to sync kill score across all servers)
# - local database (DEFAULT) (use if you only have one single server)
#
# online database is complex to setup, use only if you know what is mysql is and how to operate a online database
# online database tutorial is coming soon to help un-experienced users!
#-------------------------------------------------------------------------------------------------------------------------

# - local - online
storage-method: "local"

database:
  # The maximum number of simultaneous SQL queries
  # Recommended: 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 2

  # currently only supports mySQL
  type: "mysql"

  #mysql database settings
  mysql:
    host: "127.0.0.1"
    # Avoid using the "root" user for security reasons.
    username: "root"
    password: ""
    schema: ""
